api/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from . import views

app_name = 'api'
urlpatterns = [
    path('', include('webclient.urls'), name='webclient'),
    path('api-key/', views.ApiKeyDetailView.as_view(), name='api-key'),
    path('gathering/', include('gathering.urls', namespace="api-gathering")),
    path('users/', include('users.urls', namespace="api-users")),
]

formular/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webclient.urls'), name='webclient'),
    path('api/', include('api.urls', namespace='api')),
]

gathering/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from . import views

app_name = 'gathering'
urlpatterns = [
    path('categories/<int:category_id>/full_questions/', views.FullQuestions.as_view(), name='questions-full-list'),
    path('categories/', views.CategoryList.as_view(), name='category-list'),
    path('categories/<int:category_id>/questions/', views.QuestionList.as_view(), name='question-list'),
    path('questions/<int:question_id>/choices/', views.QuestionChoicesList.as_view(), name='question-choice-list'),
    path('question/<int:question_id>/', views.QuestionDetail.as_view(), name='question-detail'),
    path('forms/<int:company_id>/', views.FormList.as_view(), name='form-list'),
    path('answer/', views.AnswerCreate.as_view(), name='answer-create'),
    path('form/<int:form_id>/detail', views.AnswersFormDetail.as_view(), name='form-detail'),
]

webclient/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views


app_name = 'webclient'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('start-gathering/', views.StartGathering.as_view(), name="start-gathering"),
    path('select-company/', views.SelectCompany.as_view(), name="select-company"),
    path('gathering-form/', views.GatheringForm.as_view(), name="gathering-form"),
    path('form-history/', views.FormHistory.as_view(), name="form-history"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="/"), name='logout'),
    path('recover-password/', views.ResetPasswordView.as_view(), name='recover_password'),
    path('export/<int:form_id>/pdf/', views.export_form_pdf, name='export_form_pdf'),
    path('send_email/<int:form_id>/', views.send_form_email, name='send_email'),
]

webclient/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

gathering/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from rest_framework import generics, status
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView

from django.shortcuts import render

from api.helpers import get_api_user

from .models import Category, Question, QuestionChoice, Form, Answer
from .serializers import CategorySerializer, QuestionSerializer, QuestionChoiceSerializer,\
                         FormSerializer, AnswerSerializer, QuestionDetailSerializer,\
                         FullQuestionsSerializer
from users.models import Company


class CategoryList(generics.ListAPIView):
    """Api para obtener las categorias de preguntas
    """

    serializer_class = CategorySerializer
    queryset = Category.objects.filter(is_active=True).order_by('weight')


class QuestionList(generics.ListAPIView):
    """Api para obtener las preguntas de una categoría en 
    específico
    """

    serializer_class = QuestionSerializer

    def get_queryset(self):
        queryset = Question.objects.all().order_by('weight')
        category_id = self.kwargs['category_id']
        if category_id:
            queryset = queryset.filter(category=category_id, is_active=True)
        return queryset


class QuestionChoicesList(generics.ListAPIView):
    """Api para obtener la lista de opciones de una pregunta cuando
    es de tipo "SELECCION"
    """

    serializer_class = QuestionChoiceSerializer

    def get_queryset(self):
        queryset = QuestionChoice.objects.all().order_by('weight')
        question_id = self.kwargs['question_id']
        if question_id:
            queryset = queryset.filter(question=question_id)
        return queryset


class QuestionDetail(generics.ListAPIView):
    """Api para obtener los datos de una pregunta por id
    con los items
    """

    serializer_class = QuestionDetailSerializer

    def get_queryset(self):
        queryset = Question.objects.all().order_by('weight')
        question_id = self.kwargs['question_id']
        if question_id:
            queryset = queryset.filter(pk=question_id, is_active=True)
        return queryset


class FormList(generics.ListAPIView):
    """Api para listar los formularios de un paciente
    """

    serializer_class = FormSerializer

    def get_queryset(self):
        queryset = Form.objects.all().order_by('date')
        company_id = self.kwargs['company_id']
        if company_id:
            queryset = queryset.filter(company_id=company_id)
        return queryset


class FullQuestions(generics.ListAPIView):
    """Api para retornar todas las categorías con sus preguntas
    """

    serializer_class = FullQuestionsSerializer

    def get_queryset(self):
        queryset = Question.objects.all().order_by('weight')
        category_id = self.kwargs['category_id']
        if category_id:
            queryset = queryset.filter(category=category_id, is_active=True)
        return queryset


class AnswerCreate(APIView):
    """Api para crear las respuestas de un formulario de un paciente
    """

    def post(self, request):
        user = get_api_user(request)
        for answer in request.data:
            if answer['question'] == 'company_id':
                company = Company.objects.get(id=answer['value'])
                form = Form(
                    user=user,
                    company=company
                )
                form.save()
        
        answer_questions = []
        if form is not None:
            questions = Question.objects.all()
            for answer in request.data:
                if answer['question'] != 'company_id':
                    question = Question.objects.get(pk=answer['question'])
                    if question.question_type != Question.SELECCION:
                        instance = Answer(
                            form=form,
                            question=question,
                            value=answer['value']
                        )
                        instance.save()
                        answer_questions.append(instance.question)
                    elif question.question_type == Question.BOOLEANO:
                        instance = Answer(
                            form=form,
                            question=question,
                            value=True,
                        )
                        instance.save()
                        answer_questions.append(instance.question)
                    else:
                        choice = QuestionChoice.objects.get(pk=answer['value'])
                        instance = Answer(
                            form=form,
                            question=question,
                            value=str(choice.value),
                            choice=answer['value']
                        )
                        instance.save()
                        answer_questions.append(instance.question)
            
            questions = Question.objects.all()
            no_answers = []
            [no_answers.append(x) for x in questions if x not in answer_questions]

            for a in no_answers:
                instance = Answer(
                    form=form,
                    question=a,
                    value='off'
                )
                instance.save()

            response = {'detail': "Formulario creado correctamente"}
            stat = status.HTTP_201_CREATED
        else:
            response = {'detail': "Ocurrió un error inesperado"}
            stat = status.HTTP_400_BAD_REQUEST

        return Response(response, status=stat)


class AnswersFormDetail(generics.ListAPIView):
    """Api para listar las respuestas de un formulario
    """

    serializer_class = AnswerSerializer

    def get_queryset(self):
        queryset = Answer.objects.all()
        form_id = self.kwargs['form_id']
        if form_id:
            queryset = queryset.filter(form=form_id).order_by('question__category__name')
        return queryset

webclient/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django_xhtml2pdf.utils import generate_pdf

from rest_framework.authentication import BasicAuthentication 

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.template import loader
from django.utils.datastructures import MultiValueDictKeyError
from django.views.generic import TemplateView, View, ListView

from api.helpers import CsrfExemptSessionAuthentication
from gathering.models import Form, Answer
from users.models import UserToken, Company


class HomePageView(TemplateView):
    """ Index de la plataforma
    """

    template_name = 'home/home.html'


class StartGathering(LoginRequiredMixin, TemplateView):
    """Vista antes de comenzar el formulario
    """

    template_name = 'gathering/start_gathering.html'
    login_url = '/'
    redirect_field_name = 'next'


class GatheringForm(LoginRequiredMixin, TemplateView):
    """ Vista del Formulario
    """

    authentication_classes = (CsrfExemptSessionAuthentication, BasicAuthentication)
    template_name = 'gathering/gathering_form.html'
    login_url = '/'
    redirect_field_name = 'next'

    def post(self, request, *args, **kwargs):
        company_id = request.POST['company_id']
        context = {
            'company': company_id
        }
        return render(request, 'gathering/gathering_form.html', context)


class SelectCompany(LoginRequiredMixin, TemplateView):
    """Vista para seleccionar la empresa a la cual se le hará 
    la toma de requerimientos
    """

    template_name = 'gathering/select_company.html'
    login_url = '/'
    redirect_field_name = 'next'


class LoginView(View):
    """Iniciar Sesión 
    """

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            url = reverse('webclient:start-gathering')
            login(request, user)
        else:
            response = {'error': 'Correo y/o contraseña incorrectas.'}
            return JsonResponse(response, status=400)

        return JsonResponse(url, safe=False)


class ResetPasswordView(TemplateView):
    """Vista para Recuperar la constraseña
    """

    template_name = 'users/reset_password.html'

    def post(self, request, *args, **kwargs):
        try:
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = get_user_model().objects.filter(email=email)[0]
            user.set_password(password)
            user.save()
            user_token = UserToken.objects.get(user=user)
            user_token.is_use_token = True
            user_token.save()
            
            messages.add_message(
                request,
                messages.ERROR, 
                "!Felicitaciones!, tu contraseña se ha cambiado correctamente, ahora puedes ingresar con tu nueva contraseña"
            )
            return HttpResponseRedirect(reverse('webclient:home'))
            
        except MultiValueDictKeyError:
            messages.add_message(
                request,
                messages.ERROR, 
                "No hemos podido cambiar tu contraseña debido a un error inesperado"
            )
        return HttpResponseRedirect(reverse('webclient:home'))		

    def get(self, request, *args, **kwargs):
        try:
            token = request.GET.get('token')
            try:
                user = UserToken.objects.get(is_use_token=False, password_activation_token=token)
            except UserToken.DoesNotExist:
                messages.add_message(
                    request,
                    messages.ERROR, 
                    "Lo sentimos el enlace al que intenta acceder ha dejado de funcionar"
                )
                return HttpResponseRedirect(reverse('webclient:home'))

            context = self.get_context_data(user.user)
            return self.render_to_response(context)

        except MultiValueDictKeyError as e:
            return HttpResponseRedirect(reverse('webclient:home'))

        context = self.get_context_data()
        return self.render_to_response(context)
    
    def get_context_data(self,user=None, **kwargs):
        context = super(ResetPasswordView, self).get_context_data(**kwargs)
        context['user'] = user
        return context
    

class FormHistory(LoginRequiredMixin, ListView):

    model = Form
    login_url = '/'
    redirect_field_name = 'next'
    template_name = 'gathering/form_history.html'

    def get_queryset(self):
        queryset = super(FormHistory, self).get_queryset()
        queryset = Form.objects.filter(user=self.request.user)
        return queryset

    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            pass
        else:
            user = request.user
            forms = Form.objects.filter(user=user)
            if not forms:
                redirect_url = 'webclient:start-gathering'
                return redirect(reverse(redirect_url))
        self.object_list = self.get_queryset()
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


def export_form_pdf(request, form_id=None):
    """Función para descargar el formulario en pdf
    """
    form = Form.objects.get(pk=form_id)
    context = {
        'headers': (
            'Categoría',
            'Pregunta',
            'Respuesta',
        ),
        'answers': Answer.objects.filter(form=form).order_by('question__category__name'),
        'company': form.company,
        'date': form.date
    }
    report_template_name = 'forms/forms.html'
	
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="form.pdf"'
    result = generate_pdf(report_template_name, file_object=response, context=context)
    return response


def send_form_email(request, form_id=None):
    """Función para enviar un email con el formulario
    """

    form = Form.objects.get(pk=form_id)
    context = {
        'headers': (
            'Categoría',
            'Pregunta',
            'Respuesta',
        ),
        'answers': Answer.objects.filter(form=form).exclude(question__question_type='TA').order_by('question__category__name'),
        'answers_ta': Answer.objects.filter(form=form, question__question_type='TA').order_by('question__category__name'),
        'company': form.company,
        'date': form.date
    }
    template = 'emails/form-email.html'
    body = loader.get_template(template).render(context)
    message = EmailMessage("Detalle de Formulario", body, "no-reply@formular.com", [settings.EMAIL_USER])
    message.content_subtype = 'html'
    message.send()

    messages.add_message(
        request,
        messages.ERROR, 
        "Correo enviado correctamente!"
    )

    return HttpResponseRedirect(reverse('webclient:form-history'))	

webclient/templates/gathering/form_history.html
{% extends 'webclient/base.html' %}
{% load static %}

{% block extra_css%}
    <link rel="stylesheet" href="{% static '/assets/css/datatables.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
{% endblock %}

{% block nav_buttons %}
    <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'webclient:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webclient:start-gathering' %}">Toma de requerimientos</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'webclient:form-history' %}">Historial de Formularios</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="title-1">Nuevo Formulario</h1>
            <p>Desde aqui podrás comenzar una nueva toma de requerimientos </p>
            <p><a class="btn btn-flat btn-lg" href="{% url 'webclient:select-company' %}" role="button">Ir al formulario &raquo;</a></p>
        </div>
    </div>
    

    <div class="container">
        <!-- Example row of columns -->
        <!-- <div class="row"> -->
            <h1>Mis formularios</h1>
            <hr>
            <table class="table table-dark" id="form-table">
                <thead>
                    <tr>
                        <th scope="col">Compañia</th>
                        <th scope="col">Fecha</th>
                        <th scope="col">Acciones</th>
                        <!-- <th scope="col">Handle</th> -->
                    </tr>
                </thead>
                <tbody>
                    {% for form in object_list %}
                        <tr>
                            <td>{{form.company|default:"Sin compañia"}}</td>
                            <td>{{form.date}}</td>
                            <td>
                                <button class="btn btn-wrapper-white btn-sized btn-detail" data-form-id={{form.id}}>Detalle</button> 
                                <a href="/export/{{form.id}}/pdf/" class="btn btn-wrapper-white btn-sized">Descargar</a>
                                <a href="/send_email/{{form.id}}/" class="btn btn-flat btn-sized">Enviar correo</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        <!-- </div> -->

        <hr>

    </div> <!-- /container -->

    <!-- Modal -->
    <div class="modal fade" id="form-detail" tabindex="-1" role="dialog" aria-labelledby="form-detail" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" >Detalle del formulario</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span class="text-white" aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table class="table" id="detail-form">
                        <thead>
                            <tr>
                                <th scope="col">Categoría</th>
                                <th scope="col">Pregunta</th>
                                <th scope="col">Respuesta</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer download">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <a href="/export/{{form.id}}/pdf/" class="btn btn-flat">Descargar</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js%}
    <script src="//cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script>
        $('.btn-detail').on('click', function(){
            form_id = $(this).data('form-id')
            $.ajax(
            {
                type: 'GET',
                headers: {'Api-Key': '{{ Api_Key}}'},
                url:"/api/gathering/form/"+form_id+"/detail",
                success:function(data)
                {
                    $('#detail-form tbody').empty()
                    $(data).each(function(k, v){
                        if (v.question.question_type == 'BO'){
                            if (v.value == 'on'){
                                value = '<i class="fas fa-check"></i>'
                            }
                            else{
                                value = '<i class="fas fa-times"></i>'
                            }
                        }
                        else {
                            value = v.value
                        }
                        $('#detail-form tbody').append(
                            `<tr>
                                <td>${v.question.category.name}</td>
                                <td>${v.question.context}</td>
                                <td>${value}</td>
                            </tr>`
                        )
                    })
                    $('.modal-footer').empty()
                    $('.modal-footer').append(
                        `<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>`+
                        `<a href="/export/${form_id}/pdf/" class="btn btn-flat">Descargar</a>`
                    )
                    
                },
                error:function(data)
                {
                    data = data.responseJSON
                    $.each(data, function(k, v)
                    {
                        toastr.options = {
                            "closeButton": false,
                            "debug": false,
                            "newestOnTop": false,
                            "progressBar": false,
                            "positionClass": "toast-top-right",
                            "preventDuplicates": true,
                            "onclick": null,
                            "showDuration": "1000",
                            "hideDuration": "1000",
                            "timeOut": "5000",
                            "extendedTimeOut": "1000",
                            "showEasing": "swing",
                            "hideEasing": "linear",
                            "showMethod": "fadeIn",
                            "hideMethod": "fadeOut"
                        }
                        toastr.error(v)
                    });
                    submitButton.removeClass('disabled')
                    submitButton.attr('disabled', false)
                }
            });
   
            $('#form-detail').modal('toggle')
        })
        $(document).ready( function () {
            $('#form-table').DataTable({
                language: {
                    "sProcessing":     "Procesando...",
                    "sLengthMenu":     "Mostrar _MENU_ registros",
                    "sZeroRecords":    "No se encontraron resultados",
                    "sEmptyTable":     "Ningún dato disponible en esta tabla",
                    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix":    "",
                    "sSearch":         "Buscar:",
                    "sUrl":            "",
                    "sInfoThousands":  ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst":    "Primero",
                        "sLast":     "Último",
                        "sNext":     "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
            });
        } );
    </script>
{% endblock %}

webclient/templates/gathering/start_gathering.html
{% extends 'webclient/base.html' %}
{% load static %}

{% block nav_buttons %}
    <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'webclient:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'webclient:start-gathering' %}">Toma de requerimientos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webclient:form-history' %}">Historial de Formularios</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    {% if request.user.is_anonymous %}
        <div class="jumbotron">
            <div class="container">
                <h1 class="title-2">Iniciar</h1>
                <h1 class="title-1">Sesión</h1>
                <p>Primero debes iniciar sesión antes de continuar</p>
                <button type="button" class="btn btn-flat" data-toggle="modal" data-target="#modal-login">
                    Iniciar Sesión
                </button>
            </div>
        </div>
        
    {% else %}
        <div class="jumbotron">
            <div class="container">
                <h1 class="title-2">Comenzar</h1>
                <h1 class="title-1">Formulario</h1>
                <p>Desde aqui podrás comenzar una nueva toma de requerimientos</p>
                <p><a class="btn btn-flat btn-lg" href="{% url 'webclient:select-company' %}" role="button">Ir al formulario &raquo;</a></p>
            </div>
        </div>
    {% endif %}
{% endblock %}