api/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from . import views

app_name = 'api'
urlpatterns = [
    path('', include('webclient.urls'), name='webclient'),
    path('api-key/', views.ApiKeyDetailView.as_view(), name='api-key'),
    path('gathering/', include('gathering.urls', namespace="api-gathering")),
    path('users/', include('users.urls', namespace="api-users")),
]

formular/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webclient.urls'), name='webclient'),
    path('api/', include('api.urls', namespace='api')),
]

webclient/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views


app_name = 'webclient'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('start-gathering/', views.StartGathering.as_view(), name="start-gathering"),
    path('select-company/', views.SelectCompany.as_view(), name="select-company"),
    path('gathering-form/', views.GatheringForm.as_view(), name="gathering-form"),
    path('form-history/', views.FormHistory.as_view(), name="form-history"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="/"), name='logout'),
    path('recover-password/', views.ResetPasswordView.as_view(), name='recover_password'),
    path('export/<int:form_id>/pdf/', views.export_form_pdf, name='export_form_pdf'),
    path('send_email/<int:form_id>/', views.send_form_email, name='send_email'),
]

webclient/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

webclient/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django_xhtml2pdf.utils import generate_pdf

from rest_framework.authentication import BasicAuthentication 

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.template import loader
from django.utils.datastructures import MultiValueDictKeyError
from django.views.generic import TemplateView, View, ListView

from api.helpers import CsrfExemptSessionAuthentication
from gathering.models import Form, Answer
from users.models import UserToken, Company


class HomePageView(TemplateView):
    """ Index de la plataforma
    """

    template_name = 'home/home.html'


class StartGathering(LoginRequiredMixin, TemplateView):
    """Vista antes de comenzar el formulario
    """

    template_name = 'gathering/start_gathering.html'
    login_url = '/'
    redirect_field_name = 'next'


class GatheringForm(LoginRequiredMixin, TemplateView):
    """ Vista del Formulario
    """

    authentication_classes = (CsrfExemptSessionAuthentication, BasicAuthentication)
    template_name = 'gathering/gathering_form.html'
    login_url = '/'
    redirect_field_name = 'next'

    def post(self, request, *args, **kwargs):
        company_id = request.POST['company_id']
        context = {
            'company': company_id
        }
        return render(request, 'gathering/gathering_form.html', context)


class SelectCompany(LoginRequiredMixin, TemplateView):
    """Vista para seleccionar la empresa a la cual se le hará 
    la toma de requerimientos
    """

    template_name = 'gathering/select_company.html'
    login_url = '/'
    redirect_field_name = 'next'


class LoginView(View):
    """Iniciar Sesión 
    """

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            url = reverse('webclient:start-gathering')
            login(request, user)
        else:
            response = {'error': 'Correo y/o contraseña incorrectas.'}
            return JsonResponse(response, status=400)

        return JsonResponse(url, safe=False)


class ResetPasswordView(TemplateView):
    """Vista para Recuperar la constraseña
    """

    template_name = 'users/reset_password.html'

    def post(self, request, *args, **kwargs):
        try:
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = get_user_model().objects.filter(email=email)[0]
            user.set_password(password)
            user.save()
            user_token = UserToken.objects.get(user=user)
            user_token.is_use_token = True
            user_token.save()
            
            messages.add_message(
                request,
                messages.ERROR, 
                "!Felicitaciones!, tu contraseña se ha cambiado correctamente, ahora puedes ingresar con tu nueva contraseña"
            )
            return HttpResponseRedirect(reverse('webclient:home'))
            
        except MultiValueDictKeyError:
            messages.add_message(
                request,
                messages.ERROR, 
                "No hemos podido cambiar tu contraseña debido a un error inesperado"
            )
        return HttpResponseRedirect(reverse('webclient:home'))		

    def get(self, request, *args, **kwargs):
        try:
            token = request.GET.get('token')
            try:
                user = UserToken.objects.get(is_use_token=False, password_activation_token=token)
            except UserToken.DoesNotExist:
                messages.add_message(
                    request,
                    messages.ERROR, 
                    "Lo sentimos el enlace al que intenta acceder ha dejado de funcionar"
                )
                return HttpResponseRedirect(reverse('webclient:home'))

            context = self.get_context_data(user.user)
            return self.render_to_response(context)

        except MultiValueDictKeyError as e:
            return HttpResponseRedirect(reverse('webclient:home'))

        context = self.get_context_data()
        return self.render_to_response(context)
    
    def get_context_data(self,user=None, **kwargs):
        context = super(ResetPasswordView, self).get_context_data(**kwargs)
        context['user'] = user
        return context
    

class FormHistory(LoginRequiredMixin, ListView):

    model = Form
    login_url = '/'
    redirect_field_name = 'next'
    template_name = 'gathering/form_history.html'

    def get_queryset(self):
        queryset = super(FormHistory, self).get_queryset()
        queryset = Form.objects.filter(user=self.request.user)
        return queryset

    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            pass
        else:
            user = request.user
            forms = Form.objects.filter(user=user)
            if not forms:
                redirect_url = 'webclient:start-gathering'
                return redirect(reverse(redirect_url))
        self.object_list = self.get_queryset()
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


def export_form_pdf(request, form_id=None):
    """Función para descargar el formulario en pdf
    """
    form = Form.objects.get(pk=form_id)
    context = {
        'headers': (
            'Categoría',
            'Pregunta',
            'Respuesta',
        ),
        'answers': Answer.objects.filter(form=form).order_by('question__category__name'),
        'company': form.company,
        'date': form.date
    }
    report_template_name = 'forms/forms.html'
	
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="form.pdf"'
    result = generate_pdf(report_template_name, file_object=response, context=context)
    return response


def send_form_email(request, form_id=None):
    """Función para enviar un email con el formulario
    """

    form = Form.objects.get(pk=form_id)
    context = {
        'headers': (
            'Categoría',
            'Pregunta',
            'Respuesta',
        ),
        'answers': Answer.objects.filter(form=form).exclude(question__question_type='TA').order_by('question__category__name'),
        'answers_ta': Answer.objects.filter(form=form, question__question_type='TA').order_by('question__category__name'),
        'company': form.company,
        'date': form.date
    }
    template = 'emails/form-email.html'
    body = loader.get_template(template).render(context)
    message = EmailMessage("Detalle de Formulario", body, "no-reply@formular.com", [settings.EMAIL_USER])
    message.content_subtype = 'html'
    message.send()

    messages.add_message(
        request,
        messages.ERROR, 
        "Correo enviado correctamente!"
    )

    return HttpResponseRedirect(reverse('webclient:form-history'))	

formular/templates/webclient/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" >
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'assets/css/formular.css' %}">

        {% block extra_css%}
        {% endblock %}

        <title>Formular!</title>
    </head>
    <body>
        <nav class="navbar navbar-dark">
            <a class="navbar-brand" href="/">
                <img src="{% static '/assets/images/logo.png' %}" width="90" height="80" alt="uvemedia-logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                {% if request.user.is_anonymous %}
                    <button type="button" class="btn btn-flat" data-toggle="modal" data-target="#modal-login">
                        Iniciar Sesión
                    </button>
                {% else %}
                    {% block nav_buttons %}
                    {% endblock %}
                    <br>
                    <span class="text-white">Bienvenido, {{ request.user.get_full_name }}</span>
                    <a href="/logout/" id="Logout" class="btn btn-semiflat">Cerrar sesión</a>
                {% endif %}
            </div>
        </nav>

    
        <main role="main">
            {% if messages  %}
                {% for message in messages %}
                <div class="alert alert-danger">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    {{message}}
                </div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock %}
        </main>

        <!-- Modal Login -->
        <div class="modal fade" id="modal-login" tabindex="-1" role="dialog" aria-labelledby="modal-loginLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modal-loginLabel">Iniciar Sesión</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span class="text-white" aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" id="login" class="form-horizontal">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username">Usuario</label>
                                <input type="text" class="form-control" id="username" name="username" aria-describedby="emailHelp" placeholder="Ingresa tu usuario">
                            </div>
                            <div class="form-group">
                                <label for="password">Contraseña</label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="Contraseña">
                            </div>

                            <p class="text-right">
                                <a href="#modal-forget" class="forgot-pass" data-toggle="modal" data-dismiss="modal">¿Olvidaste tu contraseña?</a>
                            </p>
                        
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-flat">Iniciar Sesión</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal Recuperar contraseña -->
        <div class="modal fade" id="modal-forget" tabindex="-1" role="dialog" aria-labelledby="modal-recoverLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modal-recoverLabel">¿Olvidaste tu contraseña?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span class="text-white" aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" id="forget" class="form-horizontal">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username">Correo Electrónico</label>
                                <input type="text" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Ingresa tu correo">
                            </div>
                            <p class="text-right">
                                <a href="#modal-login" class="forgot-pass" data-toggle="modal" data-dismiss="modal">Iniciar Sesión</a>
                            </p>
                        
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-flat">Enviar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
              <span>UVEMEDIA {% now "Y" %} - Powered by Apptitud</span>
            </div>
        </footer>
    

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
        
        <script>
            $.validate({
                modules : 'html5, security',
            });
        </script>
        <!-- Script para enviar Ajax de Login -->
        <script type="text/javascript">
            $("#login").on('submit', function(ev){
                ev.preventDefault()
                console.log("Submit")
                $.ajax({
                    data: new FormData($(this)[0]),
                    cache: false,
                    contentType: false,
                    processData: false,
                    type: "POST",
                    headers: {'X-CSRFToken': '{{ csrf_token }}'},
                    url:"{% url 'webclient:login' %}",
                    success:function(data)
                    {
                        if (data.length > 0){
                            url = data['url']
                            window.location.href = data
                        }
                    },
                    error:function(data)
                    {
                        data = data.responseJSON
                        $.each(data, function(k, v)
                        {   
                            toastr.options = {
                                "closeButton": false,
                                "debug": false,
                                "newestOnTop": false,
                                "progressBar": false,
                                "positionClass": "toast-top-right",
                                "preventDuplicates": true,
                                "onclick": null,
                                "showDuration": "1000",
                                "hideDuration": "1000",
                                "timeOut": "5000",
                                "extendedTimeOut": "1000",
                                "showEasing": "swing",
                                "hideEasing": "linear",
                                "showMethod": "fadeIn",
                                "hideMethod": "fadeOut"
                            }
                            toastr.error(v)
                            
                        });
                    }
                });
            })         
        </script>

        <!-- Script para enviar Ajax de olvido contraseña -->
        <script type="text/javascript">
            $("#forget").on('submit', function(ev){
                ev.preventDefault()
                $('#reg_submit_forget').attr('disabled', true)
                $.ajax({
                    data: $(this).serialize(),
                    type: "POST",
                    headers: {'X-CSRFToken': '{{ csrf_token }}'},
                    url:"{% url 'api:users:reset_password' %}",
                    success:function(data)
                    {
                        toastr.options = {
                            "closeButton": false,
                            "debug": false,
                            "newestOnTop": false,
                            "progressBar": false,
                            "positionClass": "toast-top-right",
                            "preventDuplicates": true,
                            "onclick": null,
                            "showDuration": "1000",
                            "hideDuration": "1000",
                            "timeOut": "5000",
                            "extendedTimeOut": "1000",
                            "showEasing": "swing",
                            "hideEasing": "linear",
                            "showMethod": "fadeIn",
                            "hideMethod": "fadeOut"
                        }
                        toastr.success(data['detail'])
                        setTimeout(function(){
                            $('#modal-forget').modal('toggle')
                            location.reload()
                        }, 1500);
                    },
                    error:function(data)
                    {
                        data = data.responseJSON
                        $.each(data, function(k, v)
                        {   
                            toastr.options = {
                                "closeButton": false,
                                "debug": false,
                                "newestOnTop": false,
                                "progressBar": false,
                                "positionClass": "toast-top-right",
                                "preventDuplicates": true,
                                "onclick": null,
                                "showDuration": "1000",
                                "hideDuration": "1000",
                                "timeOut": "5000",
                                "extendedTimeOut": "1000",
                                "showEasing": "swing",
                                "hideEasing": "linear",
                                "showMethod": "fadeIn",
                                "hideMethod": "fadeOut"
                            }
                            toastr.error("El correo electrónico no se encuentra registrado")
                            
                        });
                        $('#reg_submit_forget').attr('disabled', false)
                    }
                });
            })          
        </script>

        <script type="text/javascript">
            $('#modal-login').on('hide.bs.modal', function(e){
                $('#login')[0].reset();
            })
            $('#modal-forget').on('hide.bs.modal', function(e){
                $('#forget')[0].reset();
            })
        </script>

        {% block extra_js%}

        {% endblock %}
    </body>
</html>